# Generated by Django 4.0.6 on 2022-07-30 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_messages_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'ordering': ['-date_ordered']},
        ),
        migrations.AddField(
            model_name='profile',
            name='middle_name',
            field=models.CharField(default='Adedamola', max_length=50),
        ),
    ]
