# Generated by Django 4.0.6 on 2022-08-04 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_goods_options_profile_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='middle_name',
            field=models.CharField(max_length=50),
        ),
    ]
