# Generated by Django 4.0.6 on 2022-08-07 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
