# Generated by Django 4.0.6 on 2022-08-07 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_goods_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='add_note',
            field=models.BooleanField(default=False),
        ),
    ]
