# Generated by Django 4.0.6 on 2022-08-15 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default="{% static 'images/avatar.png' %}", upload_to=''),
        ),
    ]
