# Generated by Django 4.0.6 on 2022-08-20 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_rename_add_note_goods_add_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='message',
        ),
    ]
