# Generated by Django 4.0.6 on 2022-08-20 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_remove_notification_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='product',
            new_name='good',
        ),
    ]
