# Generated by Django 4.0.6 on 2022-08-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_rename_product_notification_good'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='add_feedback',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='goods',
            name='feedback',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
