# Generated by Django 4.0.6 on 2022-08-21 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_goods_feedback_read'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='avatar',
            new_name='Picture',
        ),
    ]
