# Generated by Django 4.0.6 on 2022-08-21 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_rename_avatar_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Picture',
            new_name='picture',
        ),
    ]
