# Generated by Django 4.0.6 on 2022-09-01 10:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
