# Generated by Django 4.0.6 on 2022-09-08 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_options_alter_unitname_options'),
        ('users', '0028_alter_goods_price_alter_goods_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_good', to='products.product'),
        ),
    ]
