# Generated by Django 4.0.6 on 2022-09-22 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_alter_goods_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
