# Generated by Django 4.1.2 on 2022-10-09 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0030_alter_goods_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="goods",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
