# Generated by Django 4.0.6 on 2022-08-11 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product'),
        ('administrator', '0002_alter_staffmodel_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmodel',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_to_unit', to='products.unitname'),
        ),
    ]
