# Generated by Django 4.0.6 on 2022-08-12 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_alter_staffmodel_unit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaffModel',
        ),
    ]
