# Generated by Django 4.0.6 on 2022-08-12 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_delete_staffmodel'),
    ]

    operations = [
    ]
