# Generated by Django 4.1.2 on 2022-10-09 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_blog_slug_news_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="news",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
