# Generated by Django 4.1.2 on 2022-11-09 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_alter_blog_date_created_alter_news_date_created"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Blog",
        ),
        migrations.DeleteModel(
            name="News",
        ),
    ]
